// <auto-generated />
namespace Biblio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migration_initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201801302050502_migration_initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
