// <auto-generated />
namespace Biblio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class table_client_table_livre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(table_client_table_livre));
        
        string IMigrationMetadata.Id
        {
            get { return "201801302343522_table_client_table_livre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
